services:
  db:
      container_name: addresstool-postgres
      image: postgres:16.11-alpine3.23
      env_file:
        - addresstool-api/secret.env
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: addresstool
        PGDATA: /data/postgres
      volumes:
        - db:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - addresstool-network
      restart: unless-stopped

  addresstool-api:
    container_name: addresstool-api
    build:
      context: ./addresstool-api
      dockerfile: Dockerfile
    image: kubo1601/addresstool-api
    env_file:
      - addresstool-api/secret.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/addresstool
    ports:
      - "8089:8080"
    networks:
      - addresstool-network
    depends_on:
      - db
    restart: unless-stopped

  addresstool-frontend:
    container_name: addresstool-frontend
    build:
      context: ./addresstool-frontend
      dockerfile: Dockerfile
    image: kubo1601/addresstool-frontend
    ports:
      - "80:80"
    networks:
      - addresstool-network
    depends_on:
      - addresstool-api
    restart: unless-stopped

networks:
  addresstool-network:
    driver: bridge

volumes:
  db:
