### GET cities by postalCode
GET http://localhost:8080/addresstool/api/cityByPostalCode/3500
### GET cities by postalCode via DOCKER
GET http://localhost:8089/addresstool/api/cityByPostalCode/3500
### GET cityEntity names by postalCode
GET http://localhost:8080/addresstool/api/cityNamesByPostalCode/2000
### GET cities by name
GET http://localhost:8080/addresstool/api/cityByName/Averbode
### GET postal code by name
GET http://localhost:8080/addresstool/api/postalCodeByCityName/Averbode
### GET streets by postalcode
GET http://localhost:8080/addresstool/api/streetByPostalCode/3271
### GET streets by cityEntity
GET http://localhost:8080/addresstool/api/streetByCity/Averbode
###
GET http://localhost:8080/addresstool/api/getEuropeanCodes
