### GET cities by postalCode
GET http://localhost:8080/addresstool/api/cityByPostalCode/3500
### GET cities by postalCode via DOCKER
GET http://localhost:8089/addresstool/api/cityByPostalCode/3500
### GET city names by postalCode
GET http://localhost:8080/addresstool/api/cityNamesByPostalCode/2000
### GET cities by name
GET http://localhost:8080/addresstool/api/cityByName/Averbode
### GET pstal code by name
GET http://localhost:8080/addresstool/api/postalCodeByCityName/Averbode
###
