services:
  db:
      container_name: addresstool-postgres
      image: postgres:16.11-alpine3.23
      env_file:
        - secret.env
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - postgres
      restart: unless-stopped

#  addresstool-api:
#    container_name: addresstool-api
#    image: kubo1601/addresstool-api
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/addresstool
#    ports:
#      - "8089:8080"
#    networks:
#      - postgres
#    depends_on:
#      - db
#    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
