### POST /SAVE personEntity
POST http://localhost:8080/addresstool/api/person
Content-Type: application/json
Accept: application/json

{
  "id": null,
  "lastName": "BOETS",
  "firstName": "Kurt",
  "birthDate": "1974-01-16",
  "address": {
    "street": "Bredestraat",
    "number": 72,
    "box": null,
    "city": {
      "postalCode": "3271",
      "name": "AVERBODE",
      "isMain": false
    }
  }
}

### GET /getAllPersons
GET http://localhost:8080/addresstool/api/person/all

### GET /getbyId
GET http://localhost:8080/addresstool/api/person/8

### PUT /update personEntity
PUT http://localhost:8080/addresstool/api/person
Content-Type: application/json
Accept: application/json

{
  "id": 8,
  "lastName": "BOETS",
  "firstName": "Kurt",
  "birthDate": "1974-01-16",
  "address": {
    "street": "Bredestraat",
    "number": 72,
    "box": "a",
    "city": {
      "postalCode": "3271",
      "name": "AVERBODE",
      "isMain": false
    }
  }
}

### DELETE /deleteById personEntity
DELETE http://localhost:8080/addresstool/api/person/8
