spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/addresstool?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  application:
    name: addresstool
    version: @project.version@
  flyway:
    enabled: true
    encoding: UTF-8
    schemas: addresstool
    create-schemas: true
    default-schema: addresstool
  docker:
    compose:
      file: ./docker-compose.yaml


server:
  servlet:
    context-path: /addresstool
  port: 8080


logging:
  level:
    root: INFO
    be.boets: DEBUG
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG

