spring:
  main:
    web-application-type: servlet
  application:
    name: addresstool
  flyway:
    enabled: false
    encoding: UTF-8
  docker:
    compose:
      file: compose.yaml

server:
  servlet:
    context-path: /addresstool
  port: 8080


logging:
  level:
    root: INFO
    be.boets: DEBUG

