name: Addresstool workflow
on:
  pull_request:
    branches:
     - master
    paths:
      - addresstool-api/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./addresstool-api
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: maven clean verify
        run: mvn -B -ntp clean verify
  
