name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - addresstool-api/**
      - addresstool-frontend/**
      - .github/workflows/deploy.yml
  pull_request:
    branches:
      - master
    paths:
      - addresstool-api/**
      - addresstool-frontend/**
      - .github/workflows/deploy.yml

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: addresstool-api/
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Generate Build number
        run: |
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "Generated build number: $BUILD_NUMBER"

      - name: Build with Maven
        run: mvn -B -ntp clean verify

      - name: Check Docker Hub username
        run: echo "Docker Hub user is set"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
            docker build -t kubo1601/addresstool-api:${{ github.run_number }} \
                         -t kubo1601/addresstool-api:latest .

      - name: Push docker image
        run: |
          docker push kubo1601/addresstool-api:${{ github.run_number }}
          docker push kubo1601/addresstool-api:latest


  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: addresstool-frontend/
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build frontend Docker image
        run: | 
          docker build -t kubo1601/addresstool-frontend:${{ github.run_number }} \
                       -t kubo1601/addresstool-frontend:latest .

      - name: Push Docker image
        run: |
          docker push kubo1601/addresstool-frontend:${{ github.run_number }}
          docker push kubo1601/addresstool-frontend:latest

